version: '3.9'
services:
  shard-1:
    image: postgres:12.16-bullseye
    container_name: shard-1
    ports:
      - "5432:5432"
    env_file:
      - ./src/main/resources/.env
    restart: unless-stopped
    networks:
      - postgres_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/batch-clean-up.sh:/batch-cleanup-script.sh
      - ./db/cron.sh:/cron.sh
  shard-2:
    image: postgres:12.16-bullseye
    container_name: shard-2
    ports:
      - "5433:5432"
    env_file:
      - ./src/main/resources/.env
    restart: unless-stopped
    networks:
      - postgres_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/batch-clean-up.sh:/batch-cleanup-script.sh
      - ./db/cron.sh:/cron.sh
networks:
  postgres_network:
    driver: bridge